#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

PROG=/usr/libexec/scwebvpn/current/webvpn-agent
CONFIG=/etc/scwebvpn/agent.json

start_service() {
	[ -x "$PROG" ] || return 1
	[ -r "$CONFIG" ] || return 1

	procd_open_instance
	procd_set_param command "$PROG" run -config "$CONFIG"
	procd_set_param user webvpn
	procd_set_param respawn 3600 5 5
	procd_set_param limits core="0"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param file "$CONFIG"
	procd_close_instance
}

reload_service() {
	stop
	start
}
