#!/bin/sh /etc/rc.common

START=90
STOP=10
USE_PROCD=1

PROG=/opt/lan-remote-access/bin/dockerd
CONFIG=/opt/lan-remote-access/daemon.json

start_service() {
    mkdir -p /var/run/lan-remote

    procd_open_instance
    procd_set_param command "$PROG" --config-file "$CONFIG"
    procd_set_param env PATH=/opt/lan-remote-access/bin:/usr/sbin:/usr/bin:/sbin:/bin
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param limits nofile="1048576 1048576"
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger lan-remote-runtime
}
