worker_processes auto;

user root;

include module.d/*.module;

events {}

http {
    access_log off;
    include mime.types;
    default_type application/octet-stream;
    sendfile on;

    gzip on;
    gzip_vary on;
    gzip_proxied any;

    include conf.d/*.conf;
}
